var searchData=
[
  ['sactiveset',['sactiveset',['../structalglib__impl_1_1sactiveset.html',1,'alglib_impl']]],
  ['samesizetupleprefixcomparator',['SameSizeTuplePrefixComparator',['../structstd_1_1tr1_1_1gtest__internal_1_1SameSizeTuplePrefixComparator.html',1,'std::tr1::gtest_internal']]],
  ['samesizetupleprefixcomparator_3c_200_2c_200_20_3e',['SameSizeTuplePrefixComparator&lt; 0, 0 &gt;',['../structstd_1_1tr1_1_1gtest__internal_1_1SameSizeTuplePrefixComparator_3_010_00_010_01_4.html',1,'std::tr1::gtest_internal']]],
  ['samesizetupleprefixcomparator_3c_20k_2c_20k_20_3e',['SameSizeTuplePrefixComparator&lt; k, k &gt;',['../structstd_1_1tr1_1_1gtest__internal_1_1SameSizeTuplePrefixComparator_3_01k_00_01k_01_4.html',1,'std::tr1::gtest_internal']]],
  ['sammon',['Sammon',['../classSammon.html',1,'']]],
  ['sampling',['Sampling',['../classSampling.html',1,'']]],
  ['samplingtest',['SamplingTest',['../classSamplingTest.html',1,'']]],
  ['sboolean',['sboolean',['../structalglib__impl_1_1sboolean.html',1,'alglib_impl']]],
  ['sbooleanarray',['sbooleanarray',['../structalglib__impl_1_1sbooleanarray.html',1,'alglib_impl']]],
  ['scomplex',['scomplex',['../structalglib__impl_1_1scomplex.html',1,'alglib_impl']]],
  ['scomplexarray',['scomplexarray',['../structalglib__impl_1_1scomplexarray.html',1,'alglib_impl']]],
  ['scoped_5fptr',['scoped_ptr',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scoped_5fptr_3c_20_3a_3astd_3a_3astring_20_3e',['scoped_ptr&lt; ::std::string &gt;',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scoped_5fptr_3c_20_3a_3astd_3a_3astringstream_20_3e',['scoped_ptr&lt; ::std::stringstream &gt;',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scoped_5fptr_3c_20const_20_3a_3astd_3a_3astring_20_3e',['scoped_ptr&lt; const ::std::string &gt;',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scoped_5fptr_3c_20const_20t_20_3e',['scoped_ptr&lt; const T &gt;',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scoped_5fptr_3c_20testing_3a_3ainternal_3a_3aparamiteratorinterface_3c_20t_20_3e_20_3e',['scoped_ptr&lt; testing::internal::ParamIteratorInterface&lt; T &gt; &gt;',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scoped_5fptr_3c_20testing_3a_3ainternal_3a_3atestmetafactorybase_3c_20paramtype_20_3e_20_3e',['scoped_ptr&lt; testing::internal::TestMetaFactoryBase&lt; ParamType &gt; &gt;',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scopedtrace',['ScopedTrace',['../classtesting_1_1internal_1_1ScopedTrace.html',1,'testing::internal']]],
  ['sdescendingclustersort',['SDescendingClusterSort',['../structSDescendingClusterSort.html',1,'']]],
  ['sectiondef',['SectionDef',['../classSectionDef.html',1,'']]],
  ['seedcandidate',['SeedCandidate',['../classSeedCandidate.html',1,'']]],
  ['segment_5ft',['Segment_T',['../structSegment__T.html',1,'']]],
  ['selfile',['SelFile',['../classSelFile.html',1,'']]],
  ['selline',['SelLine',['../classSelLine.html',1,'']]],
  ['settings',['Settings',['../structAlignment_1_1AProgAlignSignificant_1_1Settings.html',1,'Alignment::AProgAlignSignificant']]],
  ['settings',['Settings',['../classExtractSubset_1_1Settings.html',1,'ExtractSubset']]],
  ['shiftcorrestimator',['ShiftCorrEstimator',['../classAlignment_1_1ShiftCorrEstimator.html',1,'Alignment']]],
  ['simplegrid',['SimpleGrid',['../classSimpleGrid.html',1,'']]],
  ['singleextremafinder',['SingleExtremaFinder',['../classExtremaFinder_1_1SingleExtremaFinder.html',1,'ExtremaFinder']]],
  ['singleextremafinder_5ftest',['SingleExtremaFinder_Test',['../classSingleExtremaFinder__Test.html',1,'']]],
  ['sinpartartrecons',['SinPartARTRecons',['../classSinPartARTRecons.html',1,'']]],
  ['sinteger',['sinteger',['../structalglib__impl_1_1sinteger.html',1,'alglib_impl']]],
  ['sintegerarray',['sintegerarray',['../structalglib__impl_1_1sintegerarray.html',1,'alglib_impl']]],
  ['sizeoptimizer',['SizeOptimizer',['../structcuFFTAdvisor_1_1SizeOptimizer.html',1,'cuFFTAdvisor']]],
  ['smlpgrad',['smlpgrad',['../structalglib__impl_1_1smlpgrad.html',1,'alglib_impl']]],
  ['smlptrnsession',['smlptrnsession',['../structalglib__impl_1_1smlptrnsession.html',1,'alglib_impl']]],
  ['snnlssolver',['snnlssolver',['../structalglib__impl_1_1snnlssolver.html',1,'alglib_impl']]],
  ['softnegativefilter',['SoftNegativeFilter',['../classSoftNegativeFilter.html',1,'']]],
  ['solutioninfo',['SolutionInfo',['../structSolver_1_1SolutionInfo.html',1,'Solver']]],
  ['solver',['Solver',['../classSolver.html',1,'']]],
  ['solver_5fnu',['Solver_NU',['../classSolver__NU.html',1,'']]],
  ['som',['SOM',['../classSOM.html',1,'']]],
  ['sparseelement',['SparseElement',['../classSparseElement.html',1,'']]],
  ['sparsematrix',['sparsematrix',['../classalglib_1_1sparsematrix.html',1,'alglib']]],
  ['sparsematrix',['sparsematrix',['../structalglib__impl_1_1sparsematrix.html',1,'alglib_impl']]],
  ['sparsematrix2d',['SparseMatrix2D',['../classSparseMatrix2D.html',1,'']]],
  ['spe',['SPE',['../classSPE.html',1,'']]],
  ['sphere',['Sphere',['../classSphere.html',1,'']]],
  ['spiderhead',['SPIDERhead',['../structImageBase_1_1SPIDERhead.html',1,'ImageBase']]],
  ['spiderhead',['SPIDERhead',['../structSPIDERhead.html',1,'']]],
  ['spline1dfitreport',['spline1dfitreport',['../structalglib__impl_1_1spline1dfitreport.html',1,'alglib_impl']]],
  ['spline1dfitreport',['spline1dfitreport',['../classalglib_1_1spline1dfitreport.html',1,'alglib']]],
  ['spline1dinterpolant',['spline1dinterpolant',['../classalglib_1_1spline1dinterpolant.html',1,'alglib']]],
  ['spline1dinterpolant',['spline1dinterpolant',['../structalglib__impl_1_1spline1dinterpolant.html',1,'alglib_impl']]],
  ['spline2dinterpolant',['spline2dinterpolant',['../classalglib_1_1spline2dinterpolant.html',1,'alglib']]],
  ['spline2dinterpolant',['spline2dinterpolant',['../structalglib__impl_1_1spline2dinterpolant.html',1,'alglib_impl']]],
  ['spline3dinterpolant',['spline3dinterpolant',['../classalglib_1_1spline3dinterpolant.html',1,'alglib']]],
  ['spline3dinterpolant',['spline3dinterpolant',['../structalglib__impl_1_1spline3dinterpolant.html',1,'alglib_impl']]],
  ['sreal',['sreal',['../structalglib__impl_1_1sreal.html',1,'alglib_impl']]],
  ['srealarray',['srealarray',['../structalglib__impl_1_1srealarray.html',1,'alglib_impl']]],
  ['stack_5ft',['stack_T',['../structstack__T.html',1,'stack_T'],['../classStack__T.html',1,'Stack_T&lt; A_Type &gt;']]],
  ['staticasserttypeeqhelper',['StaticAssertTypeEqHelper',['../structtesting_1_1internal_1_1StaticAssertTypeEqHelper.html',1,'testing::internal']]],
  ['staticasserttypeeqhelper_3c_20t_2c_20t_20_3e',['StaticAssertTypeEqHelper&lt; T, T &gt;',['../structtesting_1_1internal_1_1StaticAssertTypeEqHelper_3_01T_00_01T_01_4.html',1,'testing::internal']]],
  ['stats',['stats',['../structClassicTrainingVectors_1_1stats.html',1,'ClassicTrainingVectors']]],
  ['steerable',['Steerable',['../classSteerable.html',1,'']]],
  ['string',['String',['../classtesting_1_1internal_1_1String.html',1,'testing::internal']]],
  ['structthreadexpectationsingleimage',['structThreadExpectationSingleImage',['../structstructThreadExpectationSingleImage.html',1,'']]],
  ['structthreadrotationallyalignoneimage',['structThreadRotationallyAlignOneImage',['../structstructThreadRotationallyAlignOneImage.html',1,'']]],
  ['structthreadtasks',['structThreadTasks',['../structstructThreadTasks.html',1,'']]],
  ['structuresaux',['StructuresAux',['../classStructuresAux.html',1,'']]],
  ['svc_5fq',['SVC_Q',['../classSVC__Q.html',1,'']]],
  ['svm_5fmodel',['svm_model',['../structsvm__model.html',1,'']]],
  ['svm_5fnode',['svm_node',['../structsvm__node.html',1,'']]],
  ['svm_5fparameter',['svm_parameter',['../structsvm__parameter.html',1,'']]],
  ['svm_5fproblem',['svm_problem',['../structsvm__problem.html',1,'']]],
  ['svmclassifier',['SVMClassifier',['../classSVMClassifier.html',1,'']]],
  ['svr_5fq',['SVR_Q',['../classSVR__Q.html',1,'']]],
  ['swig_5fcast_5finfo',['swig_cast_info',['../structswig__cast__info.html',1,'']]],
  ['swig_5fconst_5finfo',['swig_const_info',['../structswig__const__info.html',1,'']]],
  ['swig_5fglobalvar',['swig_globalvar',['../structswig__globalvar.html',1,'']]],
  ['swig_5fmodule_5finfo',['swig_module_info',['../structswig__module__info.html',1,'']]],
  ['swig_5ftype_5finfo',['swig_type_info',['../structswig__type__info.html',1,'']]],
  ['swig_5fvarlinkobject',['swig_varlinkobject',['../structswig__varlinkobject.html',1,'']]],
  ['swigpyclientdata',['SwigPyClientData',['../structSwigPyClientData.html',1,'']]],
  ['swigpyobject',['SwigPyObject',['../structSwigPyObject.html',1,'']]],
  ['swigpypacked',['SwigPyPacked',['../structSwigPyPacked.html',1,'']]],
  ['symlist',['SymList',['../classSymList.html',1,'']]],
  ['symlistobject',['SymListObject',['../structSymListObject.html',1,'']]]
];
