var searchData=
[
  ['some_20type_20definitions',['Some type definitions',['../group__DataTypes.html',1,'']]],
  ['sharpening',['Sharpening',['../group__Local.html',1,'']]],
  ['split_20a_20metadata_20according_20to_20a_203d_20volume',['Split a metadata according to a 3D volume',['../group__MetadataSplit3D.html',1,'']]],
  ['some_20extensions_20related_20with_20xmipp_20programs',['Some extensions related with Xmipp programs',['../group__Programs3.html',1,'']]],
  ['sammon_20projection',['Sammon Projection',['../group__Sammon.html',1,'']]],
  ['score_5fmicrograph_20_28evaluates_20the_20score_20of_20a_20micrograph_29',['score_micrograph (Evaluates the score of a micrograph)',['../group__ScoreMicrograph.html',1,'']]],
  ['selection_20files_20_28selfiles_29',['Selection files (Selfiles)',['../group__SelFiles.html',1,'']]],
  ['signal_20processing_20windows',['Signal processing windows',['../group__SignalProcWindows.html',1,'']]],
  ['smoothly_20distributed_20fuzzy_20c_2dmeans_20self_2dorganizing_20map_20algorithm',['Smoothly Distributed Fuzzy c-means Self-Organizing Map algorithm',['../group__SmoothFuzzyCmeans.html',1,'']]],
  ['smoothly_20distributed_20gaussian_20kernel_20probability_20density_20estimator_20self_20organizing_20map',['Smoothly Distributed Gaussian Kernel Probability Density Estimator Self Organizing Map',['../group__SmoothlyGaussianStudent.html',1,'']]],
  ['som_20layouts',['SOM Layouts',['../group__SOMLayouts.html',1,'']]],
  ['self_20organizing_20map',['Self Organizing Map',['../group__SomMap.html',1,'']]],
  ['spectrum_20modelling_20by_20arma_20filters',['Spectrum modelling by ARMA filters',['../group__SpARMA.html',1,'']]],
  ['stochastic_20proximity_20embedding',['Stochastic Proximity Embedding',['../group__SPE.html',1,'']]],
  ['sampling_20_28sampling_20the_20projection_20sphere_29',['sampling (Sampling the projection sphere)',['../group__SphereSampling.html',1,'']]],
  ['spider_20file_20format',['Spider File format',['../group__Spider.html',1,'']]],
  ['spider',['Spider',['../group__SpiderInterface.html',1,'']]],
  ['spline_20interpolation',['Spline interpolation',['../group__SplineInterpolation.html',1,'']]],
  ['splines',['Splines',['../group__Splines.html',1,'']]],
  ['spline_20transform',['Spline transform',['../group__SplineTransform.html',1,'']]],
  ['steerable_20filters',['Steerable filters',['../group__Steerable.html',1,'']]],
  ['string_20utilities',['String utilities',['../group__StringUtilities.html',1,'']]],
  ['svm_20classifier',['SVM Classifier',['../group__SVMClassifier.html',1,'']]],
  ['swap_20axes_20in_20a_20volume',['Swap axes in a volume',['../group__SwapAxes.html',1,'']]],
  ['symmetrize_20_28symmetrize_20a_20volume_20or_20image_29',['symmetrize (Symmetrize a volume or image)',['../group__SymmetrizeProgram.html',1,'']]],
  ['symmetry_20handling',['Symmetry handling',['../group__SymmetryLists.html',1,'']]]
];
