var searchData=
[
  ['ctf_5festimate_5ffrom_5fmicrograph_20_28ctf_20estimation_20from_20a_20micrograph_29',['ctf_estimate_from_micrograph (CTF estimation from a micrograph)',['../group__AssignCTF.html',1,'']]],
  ['classification_20first_20split',['Classification first split',['../group__ClassificationFirstSplit.html',1,'']]],
  ['classification_20library',['Classification library',['../group__ClassificationLibrary.html',1,'']]],
  ['core_20analysis_20for_20cl2d',['Core analysis for CL2D',['../group__ClassifyCL2DCore.html',1,'']]],
  ['classification_20with_20fourier_20transform_20based_20translational_20and_20rotational_20invariants',['Classification with Fourier Transform based Translational and Rotational Invariants',['../group__ClassifyFTTRI.html',1,'']]],
  ['classify_20a_20set_20of_20images_20into_20a_20discrete_20set_20of_20classes',['Classify a set of images into a discrete set of classes',['../group__ClassifySignificant.html',1,'']]],
  ['code_20book',['Code book',['../group__CodeBook.html',1,'']]],
  ['common_20lines_20_28find_20common_20lines_20between_20projections_29',['Common Lines (find common lines between projections)',['../group__CommonLinesProgram.html',1,'']]],
  ['compare_20classes',['Compare Classes',['../group__CompareClasses.html',1,'']]],
  ['convertvol2pseudo',['ConvertVol2Pseudo',['../group__ConvertVol2Pseudo.html',1,'']]],
  ['coordinates_20micrograph_20filter',['Coordinates Micrograph Filter',['../group__CoordinatesMicrographFilters.html',1,'']]],
  ['ctf_20phase_20flip_20in_202d_20particles',['CTF Phase flip in 2D particles',['../group__Correct.html',1,'']]],
  ['ctf_5fcorrect_5famplitude3d_20_283d_20wiener_20filtering_29',['ctf_correct_amplitude3D (3D Wiener filtering)',['../group__CorrectAmplitude3D.html',1,'']]],
  ['correlation_20computer',['Correlation Computer',['../group__CorrelationComputer.html',1,'']]],
  ['cpu_20support_20class',['CPU support class',['../group__CPU.html',1,'']]],
  ['ctf_5fgroup',['ctf_group',['../group__CTFGroup.html',1,'']]],
  ['ctf_20support_20classes',['CTF support classes',['../group__CTFSupport.html',1,'']]],
  ['cuda_20bspline_20geotransformer',['Cuda BSpline GeoTransformer',['../group__CudaBSplineGeoTransformer.html',1,'']]],
  ['cuda_20correlation_20computer',['Cuda Correlation Computer',['../group__CudaCorrelationComputer.html',1,'']]],
  ['cudaextremafinder',['CudaExtremaFinder',['../group__CudaExtremaFinder.html',1,'']]],
  ['cudafft',['CudaFFT',['../group__CudaFFT.html',1,'']]],
  ['cuda_20gpu_20reconstruct_20fourier',['Cuda GPU Reconstruct Fourier',['../group__CUDAGPURecFourier.html',1,'']]],
  ['cuda_20rotation_20polar_20estimator',['Cuda Rotation Polar Estimator',['../group__CudaRotPolarEstimator.html',1,'']]],
  ['cudashiftcorrestimator',['CudaShiftCorrEstimator',['../group__CudaShiftCorrEstimator.html',1,'']]],
  ['cuda_20xmipp_20utils',['Cuda Xmipp Utils',['../group__CudaXmippUtils.html',1,'']]],
  ['cuda_20gpu_20geotransformer',['Cuda GPU GeoTransformer',['../group__GeoTransformer.html',1,'']]],
  ['cuda_20gpu_20correlation',['Cuda GPU Correlation',['../group__GpuCorrelation.html',1,'']]],
  ['ctf_5fcorrect_5fidr_20_28iterative_20data_20refinement_20for_20ctf_20amplitude_20correction_29',['ctf_correct_idr (Iterative Data Refinement for CTF amplitude correction)',['../group__IDR.html',1,'']]],
  ['classifier',['Classifier',['../group__KNN.html',1,'']]],
  ['component_20analysis',['Component Analysis',['../group__Neighbourhood.html',1,'']]],
  ['construct_20a_20low_20and_20high_20resolution_20dictionary',['Construct a low and high resolution dictionary',['../group__PDBConstructDictionary.html',1,'']]],
  ['convert_5fpdb2vol_20_28pdb_20phantom_20program_29',['convert_pdb2vol (PDB Phantom program)',['../group__PDBPhantom.html',1,'']]],
  ['cuda_20gpu_20movie_20alignment_20correlation',['Cuda GPU movie Alignment Correlation',['../group__ProgAGPUMovieAlign.html',1,'']]],
  ['classify_20kmeans_202d',['Classify Kmeans 2D',['../group__ProgClassifyKmeans2D.html',1,'']]],
  ['change_20the_20image_20gray_20values_20to_20match_20a_20volume_20projection',['Change the image gray values to match a volume projection',['../group__TransformImageGray.html',1,'']]]
];
